"use client";
import type { Metadata } from "next";
import "./globals.scss";
import FirebaseApp from "@/components/FirebaseApp/FirebaseApp";
import { UserContext } from "@/context/userContext";
import { useRef } from "react";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Wallet",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = useRef({ email: null });
  return (
    <html lang="en">
      <body>
        <FirebaseApp>
          <UserContext.Provider value={user}>{children}</UserContext.Provider>
        </FirebaseApp>
      </body>
    </html>
  );
}
