import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Wallet",
  description: "Generated by create next app",
  viewport:
    "width=device-width, initial-scale=1, user-scalable=no, maximum-scale=1.0",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
